### ISSUE TITLE
Docker uTorrent installation gives linux error

### ISSUE THREAD

**Issue by Fazatholomew** [ekho/docker-utorrent#10]
$ docker run --name torrent -v ~/torrent:/utorrent/data -v ~/torrent/setting:/utorrent/settings -p 666:8080 -p 6881:6881 --restart unless-stopped ekho/utorrent:latest
it returns:
standard_init_linux.go:211: exec user process caused "exec format error"

Docker version 19.03.8
Armbian with Ubuntu 18.04.4 LTS Bionic kernel

**Comment by VMax4** [comment]
Is it possible that uTorrent doesn't work on  ARM architecture...
