### ISSUE TITLE
Troubles with volumes binding

### ISSUE THREAD

**Issue by VMax4** [ekho/docker-utorrent#12]
Hi again, with the last update i can't again having utorrent working good...

What's happen is that i changed the configuration accordingly with your new directions and i have utorrent running but even if i see the files i was downloading, they are just frozen.
Looking into the config i see something strange, i mean, the path for the various folders look not correct to me... what could be?
I attach a pic so it's more clear
Thank you in advance

![Volumes](https://user-images.githubusercontent.com/57065378/79507939-e95e0b80-8038-11ea-9545-879cc9144f95.jpg)

**Comment by ekho** [comment]
Plz use `ekho/utorrent:legacy` or update to latest

**Comment by VMax4** [comment]
No i wanted to use the new image so, the problem was that i did't understood how to configure the various folders and bind mount the various volumes, now everything is working great.
Just a question, i don't understand what is the "temp" folder utility, i checked it several times and nothing is going to be written inside but if i don't set it with a path of my choose the docker create a volume for it, so i set it correctly and all it's ok but i don't understand why it has to exist

**Comment by ekho** [comment]
Normally it does not need to mount outside. I will remove `VOLUME ["/utorrent/temp"]` from image

**Comment by VMax4** [comment]
Ooookkkey :-)
