### ISSUE TITLE
Paths should be configured from ENVs as well

### ISSUE THREAD

**Issue by gokuu** [ekho/docker-utorrent#14]
Hi,

In the last refactor, one of the changes that had the biggest impact for me was not being able to use the `utserver.conf` file to make the configuration changes I want, as now `confd` always replaces it when the container starts.

That being said, I think that, if it was possible to override the paths (and all other properties) using ENV variables, I think it would be much more flexible. I took the liberty of opening PR #13 to do exactly this

**Comment by ekho** [comment]
Closed by #13
