### ISSUE TITLE
what is the username & password needed for the GUI?

### ISSUE THREAD

**Issue by idanizi** [ekho/docker-utorrent#16]
![image](https://user-images.githubusercontent.com/9889268/93015290-fa4b8280-f5c0-11ea-9a94-9711f4fced73.png)

**Comment by ekho** [comment]
By default username admin and a blank password.

But you can modify it using env variabes

```
-e admin_name=your-admin-name -e admin_password=your-admin-password
```

all options which can be changed can be found at https://github.com/ekho/docker-utorrent/blob/master/utserver.conf.example

**Comment by mcclone2001** [comment]
Shouldn't this be in the Read.me ?
