### ISSUE TITLE
Utorrent doesn't work with proxies anymore

### ISSUE THREAD

**Issue by darklow** [ekho/docker-utorrent#8]
Thank you for this docker image. I've been using it for a while and after recent upgrades I noticed that utorrent doesn't work with socks proxies anymore and log file is full of following errors:
```
[20190228 12:45:12] OpensslEncryptHandler::encrypt error -1(1)
[20190228 12:45:13] OpensslEncryptHandler::encrypt error -1(1)
[20190228 12:45:14] OpensslEncryptHandler::encrypt error -1(1)
[20190228 12:45:14] OpensslEncryptHandler::encrypt error -1(1)
```
 Any ideas which part of update may caused this?
Tried searching, but couldn't find any solutions, all I know it was working earlier.
Thank you.

**Comment by ekho** [comment]
Hi @darklow 

Sorry. I dont know how can I help you. =(((((
I do not change anything in at a long time.

may be your socks proxy has self signed certificate?

**Comment by VMax4** [comment]
I don't know if it can help but in this old topic they had the same trouble

https://forum.utorrent.com/topic/80878-using-proxy-the-seedspeers-will-not-load-unless-i-remove-proxy/
